### ISSUE TITLE
Can view the contents of textfiles that don't exist on your server or the connected IP

### ISSUE THREAD

**Issue by hackerwars** [hackerwars-io/issue-tracker#18]
![image](https://user-images.githubusercontent.com/56300936/66711534-882f5400-edd9-11e9-800d-ae3ad16694d1.png)

**Comment by NoahCardoza** [comment]
fixed with https://github.com/NoahCardoza/hackerwars.io/commit/d0cf7ffd77fbba278644bd89869605fb3cad563c
