### ISSUE TITLE
Deleting a file inside of a folder causes folder file count to get confused and prevent folder deletion.

### ISSUE THREAD

**Issue by goldstinger** [hackerwars-io/issue-tracker#24]
If you delete a file while it is still inside of a folder, the folder will still think there is a file inside of that folder after it was already deleted, and prevent deleting a folder if the folder is empty.
![tUYfryg](https://user-images.githubusercontent.com/13899258/66730742-94d79a80-ee21-11e9-9141-62953cc84712.png)

**Comment by hackerwars** [comment]
fixed, currently made folders will continue to be broken but new ones should function fine.
