### ISSUE TITLE
Hacker Database notifications do not display virus version correctly.

### ISSUE THREAD

**Issue by goldstinger** [hackerwars-io/issue-tracker#34]
Should show as 'Virus Generic Miner (v1.6) isn't responding anymore from IP <Print IP Here>'.
![uW4dQPl](https://user-images.githubusercontent.com/13899258/67195764-91b35000-f3c7-11e9-9fbb-fa95d28db0ef.png)

**Comment by hackerwars** [comment]
This has been addressed, thank you for reporting.
