### ISSUE TITLE
Include file type extension along with file name in Task Manager.

### ISSUE THREAD

**Issue by goldstinger** [hackerwars-io/issue-tracker#40]
File name used to include '.fwl', '.vcol', '.hdr' and such in the Task Manager, to distinguish exactly what type of file each process was playing with. Hard to deduce exactly which file it is, when they all have custom names.
![R01jBmJ](https://user-images.githubusercontent.com/13899258/67634948-07239280-f898-11e9-9449-e9554d66678c.png)

**Comment by hackerwars** [comment]
Will look into this soon.
