### ISSUE TITLE
URL Inject bypasses 'You have to log out first' errors.

### ISSUE THREAD

**Issue by goldstinger** [hackerwars-io/issue-tracker#42]
https://hackerwars.io/internet?ip=[Insert_IP]&action=login&user=root&pass=[Password]

When being already logged into another IP, the above URL line (when replaced with the proper IP and its associated password) bypasses the yellow logout message in login internet page, and the error message that prevents people from logging into more than one IP at the same time. Doing so causes the game to immediately log you out of the IP you're already connected to, and logs you into the IP of which was in the URL.

![GpfeKSJ](https://user-images.githubusercontent.com/13899258/67652387-10097800-f91b-11e9-86eb-a3a09863a7e9.png)

**Comment by hackerwars** [comment]
This is expected functionality for the moment, we may eventually move to POST-based logins to avoid this but no plans currently.
