### ISSUE TITLE
Bug - Able to download same software and version after hidden.

### ISSUE THREAD

**Issue by Vip3rLi0n** [hackerwars-io/issue-tracker#44]
Fix the hide function. Disable people from downloading same software and version if the software exist on hdd,but hidden. So the person need to seek or format to download the same software that being hidden. 

-Before,hiding virus and uninstall seeker.
![download](https://user-images.githubusercontent.com/21289340/67975384-eb7d0b00-fc4e-11e9-94bf-6dbbe3337d68.png)

- After, Download the virus,hide,download again and hide before installing seeker. I able to seek all of them without error.
![download](https://user-images.githubusercontent.com/21289340/67975411-f768cd00-fc4e-11e9-8319-1020c18867d9.png)

**Comment by hackerwars** [comment]
This has been fixed.
