### ISSUE TITLE
Change size of Doom after installation to be anywhere between 3gb - 5gb in size.

### ISSUE THREAD

**Issue by goldstinger** [hackerwars-io/issue-tracker#52]
Small enough to not be entirely compromising to HDD space, but big enough to not be un-removable during doom. Having it currently be 500mb + 100mb for installer, means anyone with 6 servers can install doom and get away with the virus being un-removable, as it won't fall off during a DDoS.

**Comment by hackerwars** [comment]
Doom size is now set to 2GB (installer + installed size), players will need atleast 20 servers to keep it from being wiped out due to ddos.
