### ISSUE TITLE
Instant Processing of text file 'HacKingdom'.

### ISSUE THREAD

**Issue by GayKiwi** [hackerwars-io/issue-tracker#54]
While uploading the text file "HacKingdom" to the clan server "HacKingdom" during round 3, the process showed a white page, uploaded the file instantly, created no logs on either the Clan or my localhost.

**Comment by Ni3zam** [comment]
Hello, can you provide screenshot or other kind of proof? I would like to see it😊

**Comment by hackerwars** [comment]
Unable to reproduce or look into why this happened - closing for now. Thanks for reporting.
