### ISSUE TITLE
Invalid IP Ranges on NPCs and Players

### ISSUE THREAD

**Issue by vSkilled** [hackerwars-io/issue-tracker#56]
The game has the potential to generate non-routeable and unrealistic IP addresses for players and NPCs.

0.0.0.0/8 is a non-routable IP range. IPs in any range using 0 and 255 is also incorrect as these are broadcast and anycast IP addresses.

The ranges generated should be between **1 and 254**. Not 0 and 255. 

Source from legacy (incorrect):
**NPC.class.php**
```
public function generateNPC($type){
        
        $gameIP1 = rand(0, 255);
        $gameIP2 = rand(0, 255);
        $gameIP3 = rand(0, 255);
        $gameIP4 = rand(0, 255);
        $gameIP = $gameIP1 . '.' . $gameIP2 . '.' . $gameIP3 . '.' . $gameIP4;
        $genIP = ip2long($gameIP);
```

Should be:
```
public function generateNPC($type){
        
        $gameIP1 = rand(1, 254);
        $gameIP2 = rand(1, 254);
        $gameIP3 = rand(1, 254);
        $gameIP4 = rand(1, 254);
        $gameIP = $gameIP1 . '.' . $gameIP2 . '.' . $gameIP3 . '.' . $gameIP4;
        $genIP = ip2long($gameIP);
```

**Comment by hackerwars** [comment]
This has been updated, thanks for reporting.
