### ISSUE TITLE
The final puzzle bug.

### ISSUE THREAD

**Issue by Fengist** [hackerwars-io/issue-tracker#59]
The only way I found to complete the final puzzle (turn the switches on) was to actually hack the website html.

The page is trying to load a JS file (I don't remember which) with a wrong extension of .jsx which prevents the page from displaying the actual puzzle.  Renaming this in the Chrome console to .js properly displays the puzzle.

**Comment by dracity42** [comment]
Thats the puzzle. Changing the html is part of the puzzle

**Comment by aidan-gibson** [comment]
Yep, you also had to change text/jsx to text/javascript in the same html line. Technically you are not using console, you are just directly editing the html elements. Thanks tho man, you saved me.

**Comment by Fengist** [comment]
Glad I could help.  My point is though, had I not pointed this out, would you have had a reason to inspect the page and make the changes?  How many people would find a hacking game fun but don't know the first thing about writing or, much less, editing HTML?
And to make puzzles pretty much mandatory? How many people have just been relegated to throwing their hands up in disgust?

**Comment by aidan-gibson** [comment]
I feel that dawg, I’m a CS major and I always got the impression most ppl playing this game could be in a similar boat. But honestly if there are civilians playing more power to them, hopefully this game got more ppl interested in computer shit

**Comment by Z0nure** [comment]
Can you teach me the exact way to do it? I tried changing it but still not showing the puzzle.

**Comment by hackerwars** [comment]
Not a bug - this is intended until further whois or puzzle trails are implemented.
