### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by xBlackElite** [hackerwars-io/issue-tracker#62]
- Queue file deletes to delete the software that was hidden by someone else.
- Visual bug on tab "DDOS" after launching one

![Screenshot_2](https://user-images.githubusercontent.com/58535535/70191541-fcf38000-16f0-11ea-9689-06b405bd235d.png)

**Comment by hackerwars** [comment]
First issue has been addressed - Visual bug I was unable to reproduce. Thank you for reporting.
