### ISSUE TITLE
i cant do any missions

### ISSUE THREAD

**Issue by spacecatplayz** [hackerwars-io/issue-tracker#63]
whenever I click accept on a message it says "You must first complete the tutorial from Certification 2."
but unless if im just dumb, im fairly sure I have.
![image](https://user-images.githubusercontent.com/58895415/78195239-31800a00-744d-11ea-9879-40e08570a71d.png)

![image](https://user-images.githubusercontent.com/58895415/78195295-4b215180-744d-11ea-8a9e-582e8c85bf93.png)

**Comment by gresendesa** [comment]
same here. Could anyone fix this thing? 7 months since this issue was opened

**Comment by hackerwars** [comment]
This has now been fixed. Thank you for reporting.
