### ISSUE TITLE
Turn the swtches on

### ISSUE THREAD

**Issue by Z0nure** [hackerwars-io/issue-tracker#65]
The Turn the switches on is not opening/showing

![image](https://user-images.githubusercontent.com/19632133/83384410-cb4a4000-a419-11ea-92d8-7b592a2cbf5b.png)

**Comment by XG009** [comment]
To makers of hacker wars,
There is a mistype in the code of this page here:
<script src="puzzle/lightsout/index.jsx" type="text/jsx"></script>
it should be:
<script src="puzzle/lightsout/index.js" type="text/jsx"></script>
if you want to do the puzzle you can inspect the code.

**Comment by hackerwars** [comment]
Not a bug - this is intended until further whois or puzzle trails are implemented.
