### ISSUE TITLE
When going over icons that display tooltips, tooltips are displayed at the top left corner of the screen

### ISSUE THREAD

**Issue by sinraw7x** [hackerwars-io/issue-tracker#8]
Title ^

![](http://0x0.st/zxAt.gif)

**Comment by hackerwars** [comment]
can't reproduce it in the latest versions of firefox or chome, maybe an issue caused by the dark theme plugin/extension?

**Comment by sinraw7x** [comment]
It seems to be fixed now, it wasn't caused by the dark theme extension, I tried with it disabled and it also happened
