### ISSUE TITLE
safenet

### ISSUE THREAD

**Issue by ninja3135** [hackerwars-io/issue-tracker#80]
I still get on safenet list for deleting files (even though you said it nolonger does for deleting files
![hackerwars](https://user-images.githubusercontent.com/100027769/154800948-d8237f5a-0b80-4179-836f-49bb14074047.jpg)
)

**Comment by hackerwars** [comment]
It is still possible to be put on safenet for deleting files, this should only not happen when deleting files on your own system or your clan server.
