### ISSUE TITLE
Urgent - Doom Virus Bug

### ISSUE THREAD

**Issue by Raizarx97** [hackerwars-io/issue-tracker#83]
There is currently a bug where a user can launch the Doom Virus from their clan and then delete their clan. However, the launching is still running but it's not possible to launch any attacks to the source since the IP doesn't exist anymore, so basically, a whole month of upgrading software, hardware and earning money is useless since basically the round will be won by the first person that launch the virus and take advantage of this bug.

![image](https://user-images.githubusercontent.com/104740104/166168057-842fc1a0-8d6a-426d-b3ab-54a336dcedd4.png)

As you can see in the image above, it's blank before "is dooming the internet at...".

![image](https://user-images.githubusercontent.com/104740104/166168063-31c81350-b233-4aec-9a84-9b9edb3c1335.png)

This bug makes the end of round so boring since the point of the storyline is lost completely.

**Comment by hackerwars** [comment]
This has been fixed
