### ISSUE TITLE
Mission Level help link incorrect

### ISSUE THREAD

**Issue by tehstu** [hackerwars-io/issue-tracker#84]
When selecting the Mission Level help [?] icon the game loads a page which does not exist. Tried in latest stable Firefox and Edge.

![image](https://user-images.githubusercontent.com/49525833/166831907-23602ab9-e0b7-42bd-9b02-48de76c84c6b.png)

**Steps to reproduce**:

1. Select Missions from left nav bar
2. In the Mission Level box on the right, click the blue [?] icon

**Observed**:
Game attempts to open https://wiki.hackerwars.io/en:missions#mission_level and reports 404 error

**Expected**:
I'm guessing the game should actually attempt to open this page from the Wiki: https://wiki.hackerwars.io/doku.php?id=en:missions#mission_level

**Comment by hackerwars** [comment]
This has been fixed, thanks for creating the issue!
