### ISSUE TITLE
Can't login to already hacked server without sufficient cracker running

### ISSUE THREAD

**Issue by TheNieznany** [hackerwars-io/issue-tracker#85]
So, I hacked a certain server that I was able to access, but after disabling a sufficient cracker I lost access, I get an error that my cracker is not good enough, even though I have the root password to that server.

![hackerwars1](https://user-images.githubusercontent.com/40523906/180644088-875725fa-cb70-4ac2-b360-b08a53949ca6.png)
![hackerwars2](https://user-images.githubusercontent.com/40523906/180644094-f89e65ad-711c-4831-ab8b-ebaf307be499.png)

**Comment by hackerwars** [comment]
I know this probably seems backwards but this is intended functionality, unsure if we will look into changing this in the future. If we do, we will announce it.
